import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Socials from "./_components/Socials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DLeite Bakery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-x-clip max-w-full  `}
    >
      <body className="flex flex-col  h-dvh w-full max-w-full overflow-hidden ">
        <Header />
        <main className="flex-1 px-12 pt-10   justify-center items-center xl:px-48  md:px-24 overflow-y-auto ">
          {/* className=" flex flex-col justify-center items-center" */}
          {children}
          <Socials />
        </main>
      </body>
    </html>
  );
}
