import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../_components/Header";
import Socials from "../_components/Socials";
import CookieBanner from "../_components/CookieBanner";
import { getDictionary } from "@/lib/getDictionaries";
import Analytics from "../_components/Analytics";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DLeite Bakery",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: "en" | "es" | "gl" }>;
}) {
  const { locale } = await params;
  const dict = await getDictionary(locale);
  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-x-clip max-w-full  `}
    >
      <body className="flex flex-col  h-dvh w-full max-w-full overflow-hidden ">
        <Header dict={dict} locale={locale} />
        <Analytics />
        <main className="relative flex-1     justify-center items-center overflow-y-auto w-screen h-screen">
          {/* className=" flex flex-col justify-center items-center" */}
          {children}
          <CookieBanner dict={dict} />
          <Socials dict={dict} />
        </main>
      </body>
    </html>
  );
}
